Add node image building scripts
Nordix/airship-dev-tools pull request #226
Opened 2020-09-10 07:24 UTC by kashifest

This PR adds the node image building scripts with pre-baked packages

2020-09-10 07:40 UTC, maelk requested changes

2020-09-10 07:40 UTC, maelk commented on ci/images/gen_ubuntu_node_image.sh
> +export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.18.0"}
let's move right away to 1.18.8 ?

2020-09-10 07:40 UTC, maelk commented on ci/images/run_local.sh
> +  /data/id_rsa_airshipci/id_rsa_airshipci 1
that should not be changed. if it is changed, it means you gave the wrong path

2020-09-10 07:40 UTC, maelk commented on ci/scripts/image_scripts/provision_node_image.sh
> +export EPHEMERAL_CLUSTER="${EPHEMERAL_CLUSTER:-kind}"
Is this used ?

2020-09-10 07:40 UTC, maelk commented on ci/scripts/image_scripts/provision_node_image.sh
> +curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/$(KUBERNETES_BINARIES_VERSION)/bin/linux/amd64/{kubeadm,kubelet,kubectl}
how are those variables defined on the node ? Are you not getting 404's there ? Defining the variable in Packer script does not make them be defined on the machine where this script is running

2020-09-10 07:40 UTC, maelk commented on ci/scripts/image_scripts/provision_node_image.sh
> +curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/$(KUBERNETES_BINARIES_VERSION)/bin/linux/amd64/{kubeadm,kubelet,kubectl}
and curl does not fail when getting a 404, that's why the building succeeds

2020-09-10 07:46 UTC, kashifest commented on ci/images/run_local.sh
> +  /data/id_rsa_airshipci/id_rsa_airshipci 1
it didnt work for me

2020-09-10 07:46 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image.sh
> +export EPHEMERAL_CLUSTER="${EPHEMERAL_CLUSTER:-kind}"
no, removed it

2020-09-10 07:46 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image.sh
> +curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/$(KUBERNETES_BINARIES_VERSION)/bin/linux/amd64/{kubeadm,kubelet,kubectl}
yes, I was working on it as we speak

2020-09-10 07:47 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.18.0"}
ok, any idea what is the corresponding config version

2020-09-10 08:11 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +export KUBERNETES_VERSION=${KUBERNETES_VERSION:-"v1.18.0"}
done

2020-09-10 08:17 UTC, maelk commented on ci/images/run_local.sh
> +  /data/id_rsa_airshipci/id_rsa_airshipci 1
probably because you gave the wrong path when calling the script

2020-09-11 05:53 UTC, maelk commented on ci/images/run_local.sh
> +  /data/id_rsa_airshipci/id_rsa_airshipci 1
this is still incorrect

2020-09-11 05:53 UTC, maelk commented on ci/images/gen_ubuntu_node_image.sh
> +export KUBERNETES_BINARIES_CONFIG_VERSION=${KUBERNETES_BINARIES_CONFIG_VERSION:-"v0.2.7"}
do you need this here ?

2020-09-13 19:54 UTC, kashifest commented on ci/images/run_local.sh
> +  /data/id_rsa_airshipci/id_rsa_airshipci 1
changed, thanks

2020-09-13 19:54 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +export KUBERNETES_BINARIES_CONFIG_VERSION=${KUBERNETES_BINARIES_CONFIG_VERSION:-"v0.2.7"}
removed, thanks

2020-09-14 05:22 UTC, maelk commented on ci/images/gen_ubuntu_node_image.sh
> +  -var "image_name=${IMAGE_NAME}" \
you could pass the flavor here instead of relying on the environment variable in the template

2020-09-14 05:22 UTC, maelk commented on ci/images/image_builder_template.json
> +    "flavor":"{{env `image_flavor`}}"
you could default here to the 50GB and only override it in the gen_ubuntu_node_image.sh, or where needed

2020-09-14 05:22 UTC, maelk commented on ci/images/gen_ubuntu_node_image.sh
> +SOURCE_IMAGE_NAME="${CI_BASE_IMAGE}"
I would probably not rely on the CI base image for this, considering that we do some hardening there that should not be done on a default Ubuntu flavor

2020-09-14 05:56 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +SOURCE_IMAGE_NAME="${CI_BASE_IMAGE}"
humm... CI base image was used since it was already installing quite a few packages, what in particular in the hardening scripts is not desirable for a node image?

2020-09-14 06:21 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +  -var "image_name=${IMAGE_NAME}" \
done thanks

2020-09-14 06:22 UTC, kashifest commented on ci/images/image_builder_template.json
> +    "flavor":"{{env `image_flavor`}}"
done thanks

2020-09-14 06:40 UTC, kashifest commented on ci/images/gen_ubuntu_node_image.sh
> +SOURCE_IMAGE_NAME="${CI_BASE_IMAGE}"
Changed, thanks

2020-09-14 07:40 UTC, maelk approved these changes

2020-09-15 10:53 UTC, merged

2020-09-16 06:42 UTC, furkatgofurov7 commented on ci/images/image_builder_template.json
> +    "flavor":  "{{user `image_flavor`}}",
This is not working properly, I guess

2020-09-16 06:52 UTC, furkatgofurov7 commented on ci/images/image_builder_template.json
> +    "flavor":  "{{user `image_flavor`}}",
It has to be just 'flavor'

2020-09-16 06:53 UTC, smoshiur1237 commented on ci/images/image_builder_template.json
> +    "flavor":  "{{user `image_flavor`}}",
I think the variable should be flabvor instead of image_flavor.