Use Kubernetes latest release 1.20
Nordix/airship-dev-tools pull request #253
Opened 2021-01-07 09:28 UTC by fmuyassarov

Install k8s 1.120 in the target node image.

2021-01-07 09:28 UTC, fmuyassarov commented
/cc @kashifest

2021-01-07 10:31 UTC, namnx228 submitted a review, later dismissed

2021-01-22 07:44 UTC, kashifest requested changes
Few small cosmetic changes  needed, otherwise looks good, thanks for taking care of this.

2021-01-22 07:44 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image.sh
> +VERSION=1.20
Do we need default values for these or should this be hardcoded ?

2021-01-22 07:44 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image.sh
> +
can we take this in a separate script like it was for docker ?

2021-01-22 07:44 UTC, kashifest commented on ci/scripts/image_scripts/provision_node_image_centos.sh
> +sudo tar -C /usr/local/bin -xzf crictl-${CRIOCTL_VERSION}-linux-amd64.tar.gz
Same comment as above. May be a separate script

2021-01-22 07:44 UTC, kashifest commented on ci/scripts/image_scripts/upload_node_image_rt.sh
> +# Don't include image the format, only the name. CENTOS_8.2_NODE_IMAGE_K8S_v1.18.8 instead of CENTOS_8.2_NODE_IMAGE_K8S_v1.18.8.qcow2
# Don't include the image format

2021-01-22 07:57 UTC, fmuyassarov commented on ci/scripts/image_scripts/provision_node_image.sh
> +VERSION=1.20
Not sure if there will be benefit of defaulting.

2021-01-22 08:31 UTC, fmuyassarov commented on ci/scripts/image_scripts/provision_node_image.sh
> +
Yes sure. Done

2021-01-22 08:31 UTC, fmuyassarov commented on ci/scripts/image_scripts/provision_node_image.sh
> +VERSION=1.20
Fixed it.

2021-01-22 08:33 UTC, fmuyassarov commented
@kashifest Thanks for the review. Addressed your comments. Please take a look.

2021-01-22 08:39 UTC, kashifest approved these changes

2021-01-22 08:40 UTC, merged