Add scalability test setup script
Nordix/airship-dev-tools pull request #255
Opened 2021-01-26 11:42 UTC by kashifest

This PR adds the scalability test setup script which needs the ips of the VMs and then goes and sets up the whole test bed.

2021-01-26 13:26 UTC, furkatgofurov7 requested changes
Good job!
Some nits inline:

2021-01-26 13:26 UTC, furkatgofurov7 commented on tools/scalability/setup_vms.sh
> +    fi
indentation
```suggestion
        fi
```

2021-01-26 13:26 UTC, furkatgofurov7 commented on tools/scalability/vm_ip_list.txt
> +188.95.226.181
please add some note that you are expecting the first IP in the list to be the `master VM` IP

2021-02-01 12:16 UTC, kashifest commented on tools/scalability/vm_ip_list.txt
> +188.95.226.181
Done

2021-02-01 12:18 UTC, furkatgofurov7 approved these changes

2021-02-01 13:11 UTC, merged