Add renovate configuration file into this repo
Nordix/airship-dev-tools pull request #274
Opened 2021-04-06 14:57 UTC by namnx228

This PR adds renovate.json configuration file to the repo, so Renovate can work with it.

2021-04-06 15:08 UTC, namnx228 commented
/assign @fmuyassarov

2021-04-07 07:33 UTC, fmuyassarov requested changes

2021-04-07 07:33 UTC, fmuyassarov commented on renovate.json
> +    },
I think we don't prepull this image in [here](https://github.com/Nordix/airship-dev-tools/blob/fae5fafcaf47ebbc9269b14140df2f255d3a79a0/ci/scripts/image_scripts/source_cluster_container_images.sh#L6), because this is not used by integration CI, it is only prow and user who can benefit from this image. We should probably skip it here?

2021-04-07 07:33 UTC, fmuyassarov commented on renovate.json
> +    },
Would you mind to share where do we use it?

2021-04-07 07:33 UTC, fmuyassarov commented on renovate.json
> +    },
You are missing docker.io/calico/node [image](https://github.com/Nordix/airship-dev-tools/blob/70db48bf4e4850102637e38bc853256d4b9c1df7/ci/scripts/image_scripts/target_cluster_container_images.sh#L8).

2021-04-07 08:49 UTC, namnx228 commented on renovate.json
> +    },
You can find the places where this item is updated here: https://github.com/namnx228/airship-dev-tools/pull/14/files

2021-04-07 08:52 UTC, fmuyassarov commented on renovate.json
> +    },
I see. Who will ensure that once `KUBERNETES_VERSION` is updated here, the same change is made in https://github.com/metal3-io/metal3-dev-env/search?q=KUBERNETES_VERSION ?

2021-04-07 09:05 UTC, namnx228 commented on renovate.json
> +    },
Good question. I think we also need to use renovate for metal3-dev-env. Otherwise, we may need to update the Kubernetes version in the repo ourshelf, or we should ignore any PR that updates K8s version in this repo.

2021-04-08 06:40 UTC, macaptain approved these changes
Let's try Renovate!

2021-04-08 07:12 UTC, furkatgofurov7 commented on renovate.json
> +    },
@namnx228 we have to set up renovate in m3-dev-env too and maybe in other repos in the future, you are right, and mostly probably IMO, we could use [`Shareable Config Presets`](https://docs.renovatebot.com/config-presets/) feature of renovate to distribute configuration that can be reused across multiple repositories. /cc @macaptain

2021-04-08 07:23 UTC, macaptain commented on renovate.json
> +    },
@furkatgofurov7 we could certainly try it. Although I expect the metal3-dev-env renovate config will need to differ at least slightly if we run Renovate from the Nordix repo but the target of the pull request is the upstream repo owned by the metal3 org.

2021-04-08 07:29 UTC, macaptain approved these changes

2021-04-08 07:47 UTC, fmuyassarov approved these changes
Thank you!

2021-04-08 09:38 UTC, merged