Add k8s and kindest/node config to renovate.json
Nordix/airship-dev-tools pull request #333
Opened 2021-07-27 15:26 UTC by Sunnatillo

2021-07-27 15:34 UTC, furkatgofurov7 commented on renovate.json
> +     "commitMessageTopic": "kindest/node"
This looks good, question though, why do we need to define kindest/node here and also inside the  `regexManagers`?

2021-07-27 15:55 UTC, Sunnatillo commented on renovate.json
> +     "commitMessageTopic": "kindest/node"
Renovate opening PR with name Node.js if it is not defined in package rules. So, I needed to add "commitMessageTopic" value. That`s why it is defined in two places.

2021-07-27 16:00 UTC, furkatgofurov7 commented on renovate.json
> +   ],
Also, seems you are stripping down the people from the list a bit, please check again and make sure everyone is in the list

2021-07-27 16:01 UTC, furkatgofurov7 commented on renovate.json
> +   ],
Also, seems you are stripping down the people from the list a bit, please check again and make sure everyone is in the list

2021-07-28 06:52 UTC, fmuyassarov approved these changes

2021-07-28 06:52 UTC, fmuyassarov commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
you could also rely on `KUBERNETES_VERSION` var from L12, because it holds the same value as in `KIND_NODE_IMAGE_VERSION`

2021-07-28 06:56 UTC, furkatgofurov7 commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
No, `KIND_NODE_IMAGE_VERSION` is N-1 behind from `KUBERNETES_VERSION` (v1.21.2 & v1.221.1)

2021-07-28 06:58 UTC, fmuyassarov commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
here yes, but in metal3-dev-env they are the same. And the reason they are not the same here, is because Renovate didn't update the version of Kind yet.

2021-07-28 07:06 UTC, furkatgofurov7 commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
even in m3-dev-env it is N-1 version behind.

2021-07-28 07:08 UTC, fmuyassarov commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
check here:
https://github.com/metal3-io/metal3-dev-env/blob/ee6f13217c81736385d49ba1c23e0b50265f495a/lib/common.sh#L202
https://github.com/metal3-io/metal3-dev-env/blob/ee6f13217c81736385d49ba1c23e0b50265f495a/lib/common.sh#L220

2021-07-28 07:09 UTC, Sunnatillo commented on renovate.json
> +   ],
I added

2021-07-28 07:13 UTC, furkatgofurov7 commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
No, this is because yesterday renovate updated kind node image to v1.21.2 and we merged it but k8s PR is still there which is updated to v1.21.3 and not merged waiting for this PR to be merged. Check these:
[kind image PR](https://github.com/metal3-io/metal3-dev-env/pull/740)
[k8s PR](https://github.com/metal3-io/metal3-dev-env/pull/739)

2021-07-28 07:13 UTC, furkatgofurov7 reviewed
/lgtm

2021-07-28 07:14 UTC, merged

2021-07-28 07:17 UTC, fmuyassarov commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
why is it behind?

2021-07-28 07:22 UTC, furkatgofurov7 commented on ci/scripts/image_scripts/source_cluster_container_images.sh
> +    export KIND_NODE_IMAGE_VERSION=${KIND_NODE_IMAGE_VERSION:-"v1.21.1"}
no idea

2021-07-28 07:39 UTC, namnx228 requested changes
Overall, it looks good to me. Just have a couple of notices. 
- Please avoid to add a space in the head of every line in `renovate.json`. From the github point of view, it is like you made change to the whole file, so Github highlight...everything in that file. It would make easier for reviewers if only the change that you added is highlight. 
- I also left a comment in line 15

2021-07-28 07:39 UTC, namnx228 commented on renovate.json
> +     "commitMessageTopic": "kindest/node"
Why don't we need the `commitMessageTopic` for other packages, but only for `kindest/node`?

2021-07-28 08:54 UTC, Sunnatillo commented on renovate.json
> +     "commitMessageTopic": "kindest/node"
Without commitMessageTopic renovate opening a PR with name Update node.js to xx.xx. So I needed to specify kindest/node in Package rules. Other package names were correct when renovate opened a PR.