Fix incorrect path in build_ipa.sh
Nordix/airship-dev-tools pull request #374
Opened 2021-09-03 07:51 UTC by Rozzii

2021-09-03 08:32 UTC, Rozzii commented
/test-ipa

2021-09-03 08:40 UTC, fmuyassarov requested changes

2021-09-03 08:40 UTC, fmuyassarov commented on ci/scripts/image_scripts/build_ipa.sh
> +
this is redundant I think? or do we need golang before integration tests?

2021-09-03 09:15 UTC, Rozzii commented
/test-ipa

2021-09-03 09:52 UTC, fmuyassarov commented
/test-ipa

2021-09-03 12:30 UTC, Rozzii commented
/test-ipa

2021-09-03 13:35 UTC, Rozzii commented
/test-ipa

2021-09-04 17:23 UTC, fmuyassarov requested changes

2021-09-04 17:23 UTC, fmuyassarov commented on ci/jobs/openstack_ipa_and_ironic_image_building.pipeline
> +        if ((((CURRENT_END_TIME - CURRENT_START_TIME)/1000) - TIMEOUT) > 0) {
`TIMEOUT` var is not declared anywhere. You either need to declare it and use that in Line55 or harcode the same value here. I would go for the first option.

2021-09-06 05:42 UTC, Rozzii commented
/test-ipa

2021-09-06 05:52 UTC, Rozzii commented
/test-ipa

2021-09-06 07:16 UTC, Rozzii commented
/test-ipa

2021-09-06 07:16 UTC, Rozzii commented on ci/jobs/openstack_ipa_and_ironic_image_building.pipeline
> +        if ((((CURRENT_END_TIME - CURRENT_START_TIME)/1000) - TIMEOUT) > 0) {
Done.

2021-09-06 07:17 UTC, Rozzii commented
I will add log collection in a separate PR.

2021-09-06 07:31 UTC, fmuyassarov requested changes

2021-09-06 07:31 UTC, fmuyassarov commented on ci/jobs/openstack_ipa_and_ironic_image_building.pipeline
> +        timeout(time: 120, unit: 'MINUTES')
```suggestion
        timeout(time: TIMEOUT, unit: 'MINUTES')
```

2021-09-06 08:49 UTC, fmuyassarov approved these changes

2021-09-06 09:00 UTC, merged

2021-09-06 09:01 UTC, Rozzii commented
/test-ipa