Add documentation for IPA-Ironic build process
Nordix/airship-dev-tools pull request #386
Opened 2021-09-20 08:03 UTC by Rozzii

2021-09-21 10:06 UTC, fmuyassarov requested changes
Looks nice. Thank for adding it. Found to nits. Otherwise lgtm.

2021-09-21 10:06 UTC, fmuyassarov commented on wow/ipa-ironic-build.md
> +5. When the build process succeeds the newly created image will be uploaded to nordix harbor.
```suggestion
5. When the build process succeeds the newly created container image will be uploaded to nordix harbor.
```

2021-09-21 10:06 UTC, fmuyassarov commented on wow/ipa-ironic-build.md
> +[IPA](https://github.com/Nordix/ironic-python-agent). The version of the IPA repository tha will be built is specified via the `IPA_REF` abd the `IPA_BRANCH` environment variables. The `IPA_BRANCH`sp
```suggestion
[IPA](https://github.com/Nordix/ironic-python-agent). The version of the IPA repository tha will be built is specified via the `IPA_REF` and the `IPA_BRANCH` environment variables. The `IPA_BRANCH`specifies what branch of IPA will be used during the build and the `IPA_REF` specifies the git commit hash that is used to select a specific version of the repository on the branch. By using the Nordix fork of the IPA repository and custom commit hash and branch name it is possible to build versions of ipa that are not part of the [upstream IPA repository](https://opendev.org/openstack/ironic-python-agent).
```

2021-09-21 10:07 UTC, fmuyassarov commented on wow/ipa-ironic-build.md
> +5. When the build process succeeds the newly created image will be uploaded to nordix harbor.
or OCI

2021-09-23 09:56 UTC, Rozzii commented on wow/ipa-ironic-build.md
> +5. When the build process succeeds the newly created image will be uploaded to nordix harbor.
fixed.

2021-09-23 09:56 UTC, Rozzii commented on wow/ipa-ironic-build.md
> +[IPA](https://github.com/Nordix/ironic-python-agent). The version of the IPA repository tha will be built is specified via the `IPA_REF` abd the `IPA_BRANCH` environment variables. The `IPA_BRANCH`sp
fixed.

2021-09-23 10:03 UTC, fmuyassarov approved these changes

2021-09-24 10:57 UTC, merged