Add Ironic and Ironic-inspector vars in ironic image builiding process
Nordix/airship-dev-tools pull request #399
Opened 2021-09-27 14:40 UTC by smoshiur1237

This PR will add Ironic and Ironic-inspector vars in image building and export them to metadata file.

2021-09-27 14:44 UTC, smoshiur1237 commented
/cc @Rozzii 
/cc @kashifest

2021-09-28 05:48 UTC, Rozzii requested changes

2021-09-28 05:48 UTC, Rozzii commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_IMAGE_BRANCH="${IRONIC_INSPECTOR_IMAGE_BRANCH:-"master"}"
IRONIC_INSPECTOR_IMAGE_BRANCH is not in use.
IRONIC_INSPECTOR_IMAGE_REPO_REF is not in use.
IRONIC_IMAGE_BRANCH  is not in use.
If these are actually not used to checkout data then these can be removed from the pipeline as parameters and then we can get their value retrospectively after the repo was cloned.

2021-09-28 06:34 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_IMAGE_BRANCH="${IRONIC_INSPECTOR_IMAGE_BRANCH:-"master"}"
Thanks good point, will update the script.

2021-09-28 06:34 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_REFSPEC="${IRONIC_REFSPEC}"
Sure, will add the necessary repo URL.

2021-09-28 07:05 UTC, Rozzii approved these changes

2021-09-28 07:36 UTC, fmuyassarov reviewed
Aren't we missing 
```
IRONIC_INSPECTOR_REFSPEC
IRONIC_IMAGE_REPO_REF
IRONIC_IMAGE_BRANCH
IRONIC_REFSPEC
```
from the pipeline?

2021-09-28 07:36 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
I think we don't need it? the only usage I see here is adding it in `metadata.txt,` which is still redundant I believe. WDYT @Rozzii ?

2021-09-28 07:36 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_IMAGE_REPO="${IRONIC_IMAGE_REPO}"
although it doesn't hurt to add them, probably we don't need them in `metadata.txt`

2021-09-28 07:36 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="${IRONIC_INSPECTOR_REPO}"
same here

2021-09-28 07:36 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +${PROJECT_DIR}-inspector ${IRONIC_INSPECTOR_REFSPEC}
nice hack :)

2021-09-28 07:36 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_IMAGE_REPO_REF="${IRONIC_IMAGE_REPO_REF:-"HEAD"}"
just a nit, maybe you could rename it to `IRONIC_IMAGE_REPO_COMMIT`?

2021-09-28 09:33 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
Here it was added this var because  the requirement says that we need to add the repo info in metadata file.

2021-09-28 09:34 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_IMAGE_REPO="${IRONIC_IMAGE_REPO}"
This is added for the requirement from ccd.

2021-09-28 09:35 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="${IRONIC_INSPECTOR_REPO}"
Same reason as previous comment^^.

2021-09-28 09:37 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_IMAGE_REPO_REF="${IRONIC_IMAGE_REPO_REF:-"HEAD"}"
I follow the same format in JJB file, `IPA_REPO_REF` as commit hash var. If you guys agree, can change. @Rozzii

2021-09-28 09:41 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
correct, but I don't see any benefit of adding it. But not blocking too, if you think it is needed let's keep it

2021-09-28 09:50 UTC, Rozzii commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
I am not sure how clear is it for outsiders that where do we get the source code from so that is why i think it is a good idea to put the inspector repo adress into the metadata.

2021-09-28 09:53 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
+1 for that case

2021-09-28 10:27 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> +IRONIC_INSPECTOR_REPO="https://opendev.org/openstack/ironic-inspector.git"
Done

2021-09-28 10:48 UTC, smoshiur1237 commented on ci/scripts/image_scripts/start_centos_ipa_ironic_build.sh
> +  IRONIC_IMAGE_REPO="${IRONIC_IMAGE_REPO:-}" \
Is it necessary to pass `IRONIC_IMAGE_REPO`  here. As this var will get the value from `run_ibuild_ironic.sh` file.

2021-09-28 10:59 UTC, Rozzii approved these changes

2021-09-28 11:13 UTC, fmuyassarov approved these changes

2021-09-28 11:46 UTC, merged