Add git metadata logging to ipa ipa image builds.
Nordix/airship-dev-tools pull request #401
Opened 2021-09-29 23:22 UTC by Rozzii

This change also makes additional git parameters configurable.

This change adds partial fixes to metadata logging in ironic build.

2021-09-30 08:22 UTC, Rozzii commented
/test-ipa

2021-09-30 09:46 UTC, smoshiur1237 requested changes

2021-09-30 09:46 UTC, smoshiur1237 commented on ci/scripts/image_scripts/run_build_ironic.sh
> -docker logout "${IMAGE_REGISTRY}"
why are we deleting the docker logout part?

2021-09-30 09:49 UTC, Rozzii commented on ci/scripts/image_scripts/run_build_ironic.sh
> -docker logout "${IMAGE_REGISTRY}"
Good catch, thanks it wasn't intentional.

2021-09-30 09:52 UTC, Rozzii commented
/test-ipa

2021-09-30 10:36 UTC, Rozzii commented
/test-ipa

2021-09-30 11:38 UTC, smoshiur1237 requested changes
Small nits. otherwise looks good to me

2021-09-30 11:38 UTC, smoshiur1237 commented on wow/ipa-ironic-build.md
> +The costumization options provide git branch, commit and refspec customization options in case of a manually triggered IPA-Ironic build job.
```suggestion
The customization options provide git branch, commit and refspec customization options in case of a manually triggered IPA-Ironic build job.
```

2021-09-30 11:38 UTC, smoshiur1237 commented on wow/ipa-ironic-build.md
> +There is one additional type of costumization option that is called `STAGING` this controls wheter the IPA artifact will be uploaded to
same here

2021-09-30 11:39 UTC, smoshiur1237 commented on wow/ipa-ironic-build.md
> +There is one additional type of costumization option that is called `STAGING` this controls wheter the IPA artifact will be uploaded to
```suggestion
There is one additional type of customization option that is called `STAGING` this controls wheter the IPA artifact will be uploaded to
```

2021-10-01 07:08 UTC, fmuyassarov commented
/test-ipa

2021-10-01 07:30 UTC, fmuyassarov commented on ci/scripts/image_scripts/build_ipa.sh
> +BMO_COMMIT="$(git rev-parse HEAD)"
same comment as below

2021-10-01 07:30 UTC, fmuyassarov commented on ci/scripts/image_scripts/run_build_ironic.sh
> +    IRONIC_IMAGE_REPO_COMMIT="$(git rev-parse HEAD)"
what if we do it in line17 ?
`IRONIC_IMAGE_REPO_COMMIT="${IRONIC_IMAGE_REPO_COMMIT:-"git rev-parse HEAD"}"`

2021-10-01 08:27 UTC, Rozzii commented on ci/scripts/image_scripts/run_build_ironic.sh
> +    IRONIC_IMAGE_REPO_COMMIT="$(git rev-parse HEAD)"
I am doing it after everything is already cloned in the repo directories to verify that what was cloned, because there could be a situation where we pulled defaults master branch with HEAD commit but it is not useful info for the developers so we have to provide a verified git commit hash even in the case when we pulled the default maste+HEAD.

2021-10-01 08:28 UTC, Rozzii commented on ci/scripts/image_scripts/build_ipa.sh
> +BMO_COMMIT="$(git rev-parse HEAD)"
answered below

2021-10-01 08:32 UTC, fmuyassarov approved these changes
/test-ipa

2021-10-01 08:50 UTC, Rozzii commented
/test-ipa

2021-10-01 10:19 UTC, smoshiur1237 approved these changes

2021-10-01 10:19 UTC, smoshiur1237 commented
test passed, we can merge it.

2021-10-01 10:20 UTC, merged