Replace master reference with main for ironic-image
Nordix/airship-dev-tools pull request #466
Opened 2022-01-12 07:28 UTC by kashifest

2022-01-12 07:37 UTC, Rozzii commented
/test-ipa

2022-01-12 07:58 UTC, Rozzii requested changes

2022-01-12 07:58 UTC, Rozzii commented on scripts/init-repo.sh
> +    # Update "main" on Nordix
I think at this point in time when not all of the repos are configured to have a main branch  yet this change might cause problems, but I don't see this used in CI so I assume it is okay to change already.

2022-01-12 07:58 UTC, Rozzii commented on wow/github-workflow.md
> +Sometimes you may need to backport a commit (e.g. bug fix) from a main/master branch
There is a leftover "master".

2022-01-12 07:58 UTC, Rozzii commented on wow/github-workflow.md
> +specific commit from the `main`/`master` branch.
There is a leftover "master".

2022-01-12 07:58 UTC, Rozzii commented on README.md
> +## Update the nordix master/main branches
As you have modified scripts/init-repo.sh it is only main not master/main

2022-01-12 08:08 UTC, Rozzii requested changes

2022-01-12 08:08 UTC, Rozzii commented on scripts/init-repo.sh
> +    # Update "main" on Nordix
Check the end of this file, this change is only applicable after both metal3-dev-env and metal3-docs are configured to use "main" as primary branch.

2022-01-12 08:20 UTC, kashifest commented on wow/github-workflow.md
> +Sometimes you may need to backport a commit (e.g. bug fix) from a main/master branch
Done

2022-01-12 08:20 UTC, kashifest commented on wow/github-workflow.md
> +specific commit from the `main`/`master` branch.
Done

2022-01-12 08:21 UTC, kashifest commented on README.md
> +## Update the nordix master/main branches
Done

2022-01-12 08:22 UTC, kashifest commented on scripts/init-repo.sh
> +    # Update "main" on Nordix
Lets keep it since I will be doing the changes soon.

2022-01-12 08:22 UTC, kashifest commented
/test-ipa

2022-01-12 13:22 UTC, Rozzii commented
/test-ipa

2022-01-12 15:04 UTC, furkatgofurov7 commented
/test-ipa

2022-01-13 09:12 UTC, Rozzii commented
/approve

2022-01-13 09:13 UTC, Rozzii approved these changes

2022-01-13 13:10 UTC, merged